maintainer       "AT&T, Inc."
maintainer_email "jaypipes@gmail.com"
license          "Apache 2.0"
description      "The OpenStack Advanced Volume Management service Cinder."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "2012.2.0"

supports         "ubuntu"
supports         "fedora"
supports         "redhat"

depends          "mysql"
depends          "database"
depends          "openstack-common"
depends          "apt"
depends          "rabbitmq"
depends          "glance"
depends          "openstack-utils"
depends          "keystone"
depends          "openssh"
depends          "selinux"
